### ISSUE TITLE
Documentation/error:  Client

### ISSUE THREAD

**Issue by bjornasm** [ThomasLecocq/SeismoRMS#1]
Hi, great that you share this! When I try to run the example code I get the following error:

`
c = Client("ODC")
FDSNException: No FDSN services could be discovered at 'http://www.orfeus-eu.org'. This could be due to a temporary service outage or an invalid FDSN service address.`

What would be alternatives here?

**Comment by ThomasLecocq** [comment]
Hey,

BE.UCC is also available from ``IRIS`` data center !

**Comment by bjornasm** [comment]
Thank you!
