### ISSUE TITLE
 Weekday / Time of day Analysis : missing days

### ISSUE THREAD

**Issue by marcopovitch** [ThomasLecocq/SeismoRMS#12]
Hi, 

in SeismoSocialDistancing.ipynb

`days = [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']`

should be defined in `stack_wday_time(df)`

**Comment by ThomasLecocq** [comment]
true thing :)

**Comment by wminarik** [comment]
Also within stack_wday_time(df):
    return df.groupby(level=(0,1)).median().unstack(level=-1).T.droplevel(0)[days]*1e9

I get the error: Dataframe object has no attribute 'droplevel'

Unfortunately I'm not facile enough with Pandas to track it down...

**Comment by ThomasLecocq** [comment]
Hi, please update pandas , it's only in the recent versions
