### ISSUE TITLE
local time zone for clockmap

### ISSUE THREAD

**Issue by ThomasLecocq** [ThomasLecocq/SeismoRMS#16]
![image](https://user-images.githubusercontent.com/916937/80707356-1ce56f00-8aea-11ea-89eb-f29764c926b0.png)

**Comment by vhmar** [comment]
Hi,

I think something similar in clockplots
 
data[main] = localize_tz_and_reindex(data[main], "30Min")

It would have to be

data[main] = localize_tz_and_reindex(data[main], "30Min", time_zone)

**Comment by FMassin** [comment]
There a PR fixing this.
