### ISSUE TITLE
Difference in scale and colour between clock plots

### ISSUE THREAD

**Issue by wmvanstone** [ThomasLecocq/SeismoRMS#19]
![CCA1 clockplot](https://user-images.githubusercontent.com/15520612/80844407-7048e180-8bfe-11ea-86e1-7218ae10ee9d.PNG)
The clock plots are amazing and my expectations may be wrong, but:
1) I would expect the three graphs to all have the same y-axis scale, but the maximum amplitude in the top graph is 0.226nm and in the bottom graphs, it is nearly 40nm. 
2) The scale in the polar graphs goes down to -10nm, where I would expect the centre of the graph to be zero. 
3) The colours are different between the upper graph and the lower two graphs, making it hard to compare, so Wedensday is red in the top graph and green in the lower two.

**Comment by FMassin** [comment]
Is this made with the module (`seismosocialdistancing.plot()`) or within a notebook cell (previous version)?

**Comment by wmvanstone** [comment]
I am running this in the SeismoSocialDistancing.ipynb notebook, which I downloaded from here since we were asked to submit our csv files, so in the last few days. The notebook imports seismosocialdistancing.py as the last of the imports in Step 1, so I assume I am using the version of plot in that file, the code used to produce the plot is this:

seismosocialdistancing.plot(displacement_RMS,
                            type='clockplots',
                            **args)

Should I be running the code in a different way?

Thanks for everything you are doing, the plots are amazing, hopefully my comments are helping.

**Comment by FMassin** [comment]
OK. That is the last version. The amplitude difference is very annoying, looks like a processing issue, but I cannot reproduce the issue, my plots are correct... However I found a few code improvement fixing pandas compat issues that I personally had and made sure the ylim  is the same in all plots see https://github.com/ThomasLecocq/SeismoRMS/pull/19.
<img width="746" alt="Capture d’écran 2020-05-02 à 15 58 48" src="https://user-images.githubusercontent.com/10435362/80866224-d29cf300-8c8d-11ea-9ef9-773ca85b7f44.png">

**Comment by wmvanstone** [comment]
Thanks, I have fetched another copy of the code and tried again, but I still have the issue and my plots don't look exactly like yours, so for example, I don't have the missing pie slice at 23:30-24:00 or zero in the centre. Your clock amplitudes are also similar to my clock plot ones, where the standard cartesian plot has a y-axis range up to 0.225nm still. Are you suggesting I should check my version of pandas and check ylim, or is that a note for Thomas if he manages to look at it.

**Comment by FMassin** [comment]
I meant to notify @ThomasLecocq ...

**Comment by ThomasLecocq** [comment]
the 23:30-24:00 is dependent on the matplotlib version, I **think** ...

**Comment by wmvanstone** [comment]
I have upgraded my Matplotlib version in Anaconda 3, it was massively out of date, but my plots have not changed. I have tried restarting Anaconda and rebooting the computer, but the plots still haven't changed, so no 23:30-24:00 missing slice or consistent scaling of the day plot and clock plots. I was really hoping that would sort out the problem. I updated using conda update anaconda, but I might try some more update options. If I find a solution, I will let you know.

**Comment by ThomasLecocq** [comment]
Marc, it's not really an issue (I have the same on my machine, the last slice is missing). No worries, the most important for now is the RMS dataframe

**Comment by wmvanstone** [comment]
And as far as I am aware, that worked fine, I transferred the csv file to the folder and updated the spreadsheet, so that is all good. I will investigate the graph scaling for myself and let you know the outcome if I find an answer. I don't want to be irritating, but was trying to help.

**Comment by ThomasLecocq** [comment]
Marc, oki! It's good you keep reporting those issues, thanks for that!

I have to check the ylim issues as well as other hard coded stuff today, will check this too !

**Comment by ThomasLecocq** [comment]
fixed!
